### ISSUE TITLE
Flutter ios build failed

### ISSUE THREAD

**Issue by kadirpinar** [Netvent/storyly-mobile#41]
Issue tracker is **ONLY** used for reporting Flutter SDK related bugs.

Errors:
* No such module 'SDWebImage '
* Failed to build module 'Storyly' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this

## Environment Details
**Storyly SDK Version:1.8.4** ---
**Flutter SDK Version:1.22.3** ---
**Platform:**
- [ ] Android 
- [x] iOS
**Device Model:** ---
**Device OS Version:** ---
**Additional Info:**

## Steps to Reproduce

1.
2.
3.
4.

**Comment by levent-oral** [comment]
Hi @kadirpinar ,

We've updated Storyly Flutter SDK.

The issue should be resolved with version 1.8.5.

Thanks,

**Comment by Sumit-Ghosh** [comment]
@levent-oral I am using the Storyly SDK Version:1.8.6 and still not able to build.
I am running on the simulator.

```
ld: warning: ignoring file
    /Users/.../Documents/flutter_app_storyly/ios/Pods/Storyly/Storyly.xcframework/ios-arm64_armv7/Storyly.framework/Storyly
    , missing required architecture x86_64 in file
    /Users/../Documents/flutter_app_storyly/ios/Pods/Storyly/Storyly.xcframework/ios-arm64_armv7/Storyly.framework/Storyly
    (2 slices)
    Undefined symbols for architecture x86_64:
    
```
    
But If I delete this folder `ios-arm64_armv7`, then I am able to build.
It seems like it is not picking up the simulator folder from the .xcFramework .

**Comment by levent-oral** [comment]
We've updated documentation [Storyly Flutter package iOS Installation](https://integration.storyly.io/flutter/quick-start.html#ios-installation), please check that.

Quick note from there; you need to update your CocoaPods version to 1.9+ to support xcframework usage.
